export const MODULE_ID = "fist-of-the-ruby-phoenix-addons";

// --- TIME TRACKER ---
export const VISIBILITY_KEY = "time-tracker-visible";
export const TIME_TRACKING_SETTING_KEY = "time-tracker-state";
export const DEFAULT_SEGMENT_COUNT = 32;

// Goka Map Points
export const GOKA_DRAWINGS = [
  {
    shape: {
      type: "p",
      width: 300,
      height: 33,
      radius: null,
      points: [
        1.4054716347032827, 2.9490459154459137, 0, 32.893526904742906,
        2.057217190800914, 13.456442824667553, 300.3537098569334,
        17.941923766223404, 300.3537098569334, 0, 300.3537098569334,
        32.893526904742906, 300.0601062047342, 33.27340058224006,
      ],
    },
    x: 793.3229595045016,
    y: 4002.0547078942163,
    elevation: 0,
    sort: 0,
    rotation: 0,
    bezierFactor: 0,
    fillType: 0,
    fillColor: "#6028cc",
    fillAlpha: 0.5,
    strokeWidth: 8,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "",
    fontFamily: "Signika",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 135,
      height: 55,
      radius: null,
      points: [],
    },
    x: 883.4361655549152,
    y: 3948.9811058426358,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "1 Mile",
    fontFamily: "Modesto Condensed",
    fontSize: 60,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 554,
      height: 54,
      radius: null,
      points: [],
    },
    x: 873.0893080471172,
    y: 3586.6029867352063,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Mountainside Oldtown",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 361,
      height: 104,
      radius: null,
      points: [],
    },
    x: 955.4247747468928,
    y: 3287.2352977442315,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Mid Oldtown",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 414,
      height: 87,
      radius: null,
      points: [],
    },
    x: 953.97101178301,
    y: 3034.211682850324,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Seaside Oldtown",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 325,
      height: 46,
      radius: null,
      points: [],
    },
    x: 1629.9665971870816,
    y: 3092.732097694569,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Ivory Port",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 315,
      height: 59,
      radius: null,
      points: [],
    },
    x: 1729.940774995209,
    y: 2805.5407494507726,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Fallen Star",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 83,
      height: 55,
      radius: null,
      points: [],
    },
    x: 2075.4249403751896,
    y: 2601.0968030202375,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Xiao",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 197,
      height: 58,
      radius: null,
      points: [],
    },
    x: 2690.7596142022126,
    y: 1984.3195618981476,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Scale",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 371,
      height: 41,
      radius: null,
      points: [],
    },
    x: 2265.8030566385555,
    y: 1674.934482428186,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Diamond Knoll",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 334,
      height: 106,
      radius: null,
      points: [],
    },
    x: 1846.8898845876688,
    y: 1355.5404310857803,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Blue Stone",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 399,
      height: 44,
      radius: null,
      points: [],
    },
    x: 1683.4356520437123,
    y: 1540.6321331547852,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Cliffside Court",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 197,
      height: 58,
      radius: null,
      points: [],
    },
    x: 1183.7204235759973,
    y: 1527.5596205703455,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Dragonhead",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 313,
      height: 37,
      radius: null,
      points: [],
    },
    x: 2163.8307685207055,
    y: 2379.7912699207964,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "City Center",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 97,
      height: 51,
      radius: null,
      points: [],
    },
    x: 2284.5153130186886,
    y: 2155.7766995570055,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Beryl",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 98,
      height: 55,
      radius: null,
      points: [],
    },
    x: 2273.248212205148,
    y: 3151.084779188926,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Shell",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 132,
      height: 56,
      radius: null,
      points: [],
    },
    x: 2094.6278544479474,
    y: 2996.9988319547692,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Oldport",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 119,
      height: 59,
      radius: null,
      points: [],
    },
    x: 2045.4848047333621,
    y: 3239.0589569970534,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Petunia",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 213,
      height: 61,
      radius: null,
      points: [],
    },
    x: 1903.6955750697043,
    y: 3414.284734830012,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Nightingale",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 341,
      height: 57,
      radius: null,
      points: [],
    },
    x: 2247.803056638556,
    y: 3421.7384977938955,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Golden Grain",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 307,
      height: 43,
      radius: null,
      points: [],
    },
    x: 2651.158463956604,
    y: 3328.6718459135327,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Red Lantern",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 409,
      height: 61,
      radius: null,
      points: [],
    },
    x: 2399.6224986136867,
    y: 2988.035342103145,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Vermillion Wall",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 393,
      height: 47,
      radius: null,
      points: [],
    },
    x: 2246.306188951229,
    y: 2798.4902263608815,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Divine Balance",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 117,
      height: 57,
      radius: null,
      points: [],
    },
    x: 2520.099562470596,
    y: 2595.5271239321205,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Eyama",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 381,
      height: 99,
      radius: null,
      points: [],
    },
    x: 2425.8453388844964,
    y: 2268.397688158463,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Floating Lotus",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 197,
      height: 58,
      radius: null,
      points: [],
    },
    x: -527,
    y: -713,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Goka",
    fontFamily: "Modesto Condensed",
    fontSize: 100,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 556,
      height: 97,
      radius: null,
      points: [],
    },
    x: 1797.2268046092042,
    y: 2338.401045590722,
    elevation: 0,
    sort: 1,
    rotation: 285,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Thousand Mile",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 168,
      height: 58,
      radius: null,
      points: [],
    },
    x: 1395.2870563902393,
    y: 3258.8740088525838,
    elevation: 0,
    sort: 1,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Industrial Sector",
    fontFamily: "Modesto Condensed",
    fontSize: 80,
    textColor: "#ffffff",
    textAlpha: 1,
    hidden: false,
    locked: true,
    interface: false,
  },
  {
    shape: {
      type: "r",
      width: 132,
      height: 72,
      radius: null,
      points: [],
    },
    x: 2036,
    y: 1766,
    elevation: 0,
    sort: 2,
    rotation: 0,
    bezierFactor: 0.5,
    fillType: 0,
    fillColor: "#ffffff",
    fillAlpha: 0.1,
    strokeWidth: 0,
    strokeColor: "#ffffff",
    strokeAlpha: 1,
    text: "Ruby Village",
    fontFamily: "Signika",
    fontSize: 48,
    textColor: "#ff2424",
    textAlpha: 1,
    hidden: false,
    locked: false,
    interface: true,
  },
];
